### ISSUE TITLE
Map error explanations to AST

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#102]
@parthrdesai If we assume you'll have an object mapping paths to explanations, you'll have enough to create some mock data and attach explanations to the error tree for next Monday. Then you can have the different explanations show as the user hovers over local error nodes.

**Comment by elmisback** [comment]
From Bhargav:
>  a location is an array of numbers, which indexes into the child subexpression. for example in (x + 1) - x, the location of (x + 1) is [1] and the location of x is [1, 1]

(said this is 1-indexed in response to my question)

> So ideally, each explanations row, will have a new column
> this will contain the location which is an array of numbers
> Now error explanations removes common sub-expressions before doing anything. Regenerating all possible locations is apparently possible, and we can look into doing that

**Comment by parthrdesai** [comment]
I have started working on creating a mock data, still do not have anything up on UI. But most probably will be available for Monday demo.

**Comment by parthrdesai** [comment]
Have integrated comparing mock data of error location with the location of whole expression and once the location match we change the color of node to red. Next task are to get the accurate location data from explanations endpoint and display the error explanations accordingly.

**Comment by parthrdesai** [comment]
There's a small bug in assigning expression id to error explanation because when there are more than one expression error explanations are swap between expression that sets the explanation at the wrong expression. Making this 1st Priority to Fix

**Comment by parthrdesai** [comment]
The bug of expression id not correctly assigning to error explanation is fixed and created PR which updates the error explanation with node graph highlighting error node.

**Comment by parthrdesai** [comment]
Fixed the getlocations method on herbie end, changing odyssey location comparison on basis of location we get from herbie

**Comment by parthrdesai** [comment]
Odyssey now fetches correct location of error node from herbie

**Comment by parthrdesai** [comment]
Still not done with the error I am getting with herbie tests on github. Will contact herbie people and solve before this weekend

**Comment by parthrdesai** [comment]
Fixed the issue of size of map not matching, But now I have issue which gives contract error in render-phase method in timeline.rkt .

**Comment by parthrdesai** [comment]
Herbie PR merged. Created PR for odyssey end. Waiting for restart of herbie server.
