### ISSUE TITLE
SC Demo: Prep demos for application expressions

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#107]
Check off as they are prepared:
* [x] (x + 1) - x
* [x] sqrt(x + 1) - sqrt(x)
* [x] ln(x + sqrt(x*x + 1)) (asinh)
* [x] (f(x+h)^2 - f(x)^2) / h (derivative for x^2)

@benwang33: you discussed more of these with @varun10p last week, could you add those you plan to demo as checklist items below?

**Comment by elmisback** [comment]
Need to get FMA and compound interest mathjs at least

**Comment by elmisback** [comment]
For FMA, I would talk with Brett to get a story; for compound interest, I think it should be motivated enough by real-world applications, though we might need to make sure the input domain is relevant in the real world

**Comment by benwang33** [comment]
Didn't get to chat with Brett today about FMA example, will send him a dm maybe tonight (leaning towards first thing tomorrow).  

In the meantime, got the general story for Compound Interest. I couldn't find any specific cases of real life errors with the compound interest formula, but it's important to emphasize floating point error has caused huge problems in the money/finance sector. Will prep some basic slides for background info and explaining the error.

**Comment by elmisback** [comment]
Sounds good! I'm not the best example of this, but is usually good to send DMs sooner, even just with partial info, to give people heads up!

**Comment by benwang33** [comment]
Created slides and outline for Compound Interest example, I think it's going to do well. Will record video to post in Herbie channel.

May need to rethink doing Fmatest1. I spoke with Brett and although it's an interesting example, it might not be what the SC audience is looking for.

Brett also shared some good blog posts by Pavel on problems Herbie has solved in the past. We've already done the inverse hyperbolic sin, but I should dive a bit deeper.

**Comment by elmisback** [comment]
@benwang33 make sure you're updating this issue regularly with your new examples + progress! You can point to a google doc if it's easier to keep things in one place, but please update this issue with progress notifications regularly

**Comment by benwang33** [comment]
Working on making slides nicer

TODO: 
Go over Mike Lam materials 
Reach out to Cindy and Ganesh

**Comment by benwang33** [comment]
Final stretch!!!
