### ISSUE TITLE
Use react tooltip for local error mouseover info

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#123]
Instead of using the title tag, we can use react tooltip/onmouseover like other parts of the application to display important info.

**Comment by parthrdesai** [comment]
Looked up at react tooltip and its functionality, waiting for error explanations to be completed so I can start on this

**Comment by elmisback** [comment]
@zaneenders You can let Parth handle this!

**Comment by parthrdesai** [comment]
Started working considering Jaela's deselect tooltip. Mermaid graph has a complicated system so we cannot access svg while rendering so I am working on updating svg and adding a child element which is our object where we hover. Probably half way on the process, will try to get tooltip ready before Friday

**Comment by parthrdesai** [comment]
Pushed code with react tooltip in localerror to main

**Comment by elmisback** [comment]
We'll want to put the old text in the tooltip!

**Comment by parthrdesai** [comment]
Fixed all the issues with tooltip and now tooltip works perfectly in the local error component.

**Comment by elmisback** [comment]
![Image](https://github.com/user-attachments/assets/da7f46f8-83a1-46f3-89ca-9d0c3f6288c6)

**Comment by parthrdesai** [comment]
Added multiline display in tooltip. Started on implementing tooltip in error explanation component

**Comment by parthrdesai** [comment]
Merged Error Explanation and Local Error component and their respective tooltip

**Comment by parthrdesai** [comment]
Added code to display the number in the same format as error plot

**Comment by parthrdesai** [comment]
![Image](https://github.com/user-attachments/assets/30498062-c040-41e4-878e-8e38c0d33d5b)
![Image](https://github.com/user-attachments/assets/0bd524b7-43c5-4e15-86ed-f9ef9aee1b75)
Here are two reference images

**Comment by elmisback** [comment]
Looks good, closing.
