### ISSUE TITLE
Implement Odyssey support for async APIs

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#125]
- [ ] Check if the server supports async.

**Comment by zaneenders** [comment]
@parthrdesai Let me know if you need help with Async API's what got merged into `main` is slightly different then what the branch above had.

**Comment by zaneenders** [comment]
I wrote this function to test the async APIs in Herbie similarly to how we test the sync versions. So something similar might work as a starting point in Odyessy.
https://github.com/herbie-fp/herbie/blob/02e7ec5a3709ad3e06968daa97db50d636f1e44b/infra/testApi.mjs#L241

**Comment by parthrdesai** [comment]
Thanks Zane, I started working on implementing the api's which are not in odyssey. Just a quick question, the API's which are in odyssey will remain as it is right?

**Comment by zaneenders** [comment]
Oh Sorry Parth didn't see your comment.

Here is a PR implementing this issue.
https://github.com/herbie-fp/odyssey/pull/135

**Comment by elmisback** [comment]
After this is merged, we must test all endpoints/Odyssey behavior!

**Comment by zaneenders** [comment]
Edward mentioned that we should check if the server supports async in this PR.

**Comment by zaneenders** [comment]
This [PR](https://github.com/herbie-fp/odyssey/pull/135) has been merged. It does not check for async but appears to not have been needed.

**Comment by elmisback** [comment]
Checking was an idea for a way to incrementally adopt, I just switched it so now the old local binary is not used in VSCode
