### ISSUE TITLE
Look into Mike Lam's FP education materials and reach out in preparation for SC

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#130]
- [x] Ask in Herbie channel who wants to be in the meeting
- [x] Prep for meeting by reading FP education materials, look for examples we can use

You can see resources on FP teaching compiled by Mike here:

https://fpbench.org/education.html

**Comment by benwang33** [comment]
Meeting with Mike Lam scheduled for next Monday (10/14) at 1pm PST
