### ISSUE TITLE
Update component-building documentation 

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#136]
@benwang33 Set up a meeting with @jaelafield to draft a developer tutorial for how to add a new React component to Odyssey. This tutorial should show everything a new developer with little prior React experience needs to add a simple component that displays output from a tool. 

Nick Baret will be using this tutorial to add the GPU-FPX tool React component to Odyssey.

**Comment by elmisback** [comment]
This will replace the `adding_a_component.md` file in the repo root. Right now that file is not a tutorial and won't help a normal developer understand how to build a component.

**Comment by NoxNovus** [comment]
October 2 2024:
- Looked at documentation, haven't started writing new doc yet, will sync with others regarding their experiences writing new components

**Comment by elmisback** [comment]
I would start by quickly drafting the basic sections of this document alone based on what you see in the ExpressionExport component (or the FPTaylor analysis component, etc--they should all have the same steps). It doesn't hurt to talk with others, but you should be using that to fill in details after having a prototype.

**Comment by NoxNovus** [comment]
Got a preliminary draft out and feedback from @jaelafield, still in progress addressing that feedback (especially important: add images!)

**Comment by NoxNovus** [comment]
Have some images ready, but want to check in briefly about how to structure files (put everything in doc folder? images subfolder inside there? just use the pre-existing doc and image folders?)

**Comment by elmisback** [comment]
There is no current standard, so you are in charge of choosing good defaults! That said, I think the `doc` folder is the right place for documentation.

Ask for forgiveness, not permission! l can't see your work on this since nothing is pushed. That's way more inconvenient for me than anything you would have chosen.

**Comment by NoxNovus** [comment]
Will do! I'll move everything in there before the meeting

**Comment by NoxNovus** [comment]
Documentation basically wrapped up, met with Nick to test run it, everything looks good!
