### ISSUE TITLE
Add and run Selenium test with Mocha

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#139]
Use example from https://github.com/mochajs/mocha-examples/blob/main/packages/selenium/test/selenium.spec.js and our extension test file at https://github.com/herbie-fp/odyssey/blob/main/src/test/suite/extension.test.ts (or another test file--we'll want to figure out how to run tests during CI!)

**Comment by NoxNovus** [comment]
October 2 2024
- Resolved bad exit code error (seems to have been transient and related to old build)
- Tinkered with builds for tests, issues are still present
- Working on setting up Selenium tests still, will continue to update as I make progress tonight

**Comment by elmisback** [comment]
What issues were you seeing? Webpack should be building the tests automatically if I remember Tuesday correctly

**Comment by NoxNovus** [comment]
Does webpack build the tests? I thought I had to build them manually with the compile-tests (it's the same build error with the ECMAScript not recognizing export)

In any case, I just realized the error is not actually significant to the running of the tests, and it's not a blocker, but might be something to look into eventually

**Comment by NoxNovus** [comment]
The basic test is working, the next step is to figure out how to run Odyssey locally and hook Selenium up to that, my first few experiments with this didn't work, but I'm looking into just running it with something similar to one of the Odyssey build commands and then running against that URL

**Comment by elmisback** [comment]
Just assume stuff is already built and use `python -m http.server` to run a Python HTTP server in the Odyssey dir

This allows the index.html page to load in a browser, and should work the same way for Selenium

**Comment by elmisback** [comment]
See if you can get this running before RA meeting tomorrow!

**Comment by elmisback** [comment]
Also we should look into Puppeteer https://pptr.dev/

**Comment by NoxNovus** [comment]
Everything is still blank on the Odyssey sample page when I load it with the simple Python server - otherwise, I played with Puppeteer and got a toy example working.

One alternative I found was to try npm-webpack-serve, but I haven't gotten that working yet

**Comment by NoxNovus** [comment]
Ah, sorry, I misinterpreted that to mean that Live Server was used just for making the tests work, and that eventually we want a one-click or one command solution, which is what I was looking into.

I have a basic Puppeteer test working with Odyssey already with Live Server that I forgot to add in my last update, can demo that during the meeting today

**Comment by elmisback** [comment]
Awesome! Live Server is good enough to not get blocked, we can figure out a
test server soon

**Comment by elmisback** [comment]
I'm closing this issue and starting a new issue for testing!
