### ISSUE TITLE
% Accuracy average not changing on "Resample"

### ISSUE THREAD

**Issue by jaelafield** [herbie-fp/odyssey#141]
When the range for a variable is updated and "Resample" is clicked, the Accuracy (and speedup) in expressions table _should_ be updated to reflect the average over the given range. Currently, in the VSCode extension, the values do not change even when the resample clearly should've effected these values.

Original input range: -1e+308 to 1e+308
<img width="1465" alt="Screenshot 2024-09-30 at 2 40 01 PM" src="https://github.com/user-attachments/assets/04f4e316-be6a-4f4f-bbd5-188a8c600f80">

Resample new over range: 1 to 1e+308
<img width="1466" alt="Screenshot 2024-09-30 at 2 40 53 PM" src="https://github.com/user-attachments/assets/9db15f26-af53-46d9-9881-f8e0ff526659">

Incorrect accuracy also appears when using new range as the original: 1 to 1e+308
<img width="1465" alt="Screenshot 2024-09-30 at 2 41 20 PM" src="https://github.com/user-attachments/assets/63d89858-2fc1-4e14-b91b-b9296063d897">

Note that in the browser, it seems to work fine. See the correct accuracies:
<img width="1512" alt="Screenshot 2024-09-30 at 1 39 21 PM" src="https://github.com/user-attachments/assets/b45ffe10-7eae-4aa5-9453-98ec8f774d51">

(Note, this likely needs some more diagnosis & reproduction tries!)

**Comment by elmisback** [comment]
My guess is that it may have something to do with the version of the Herbie server that's running, you could try to reproduce after switching to the FPBench server, though this is low-priority relative to brushing + the codetations stuff!
