### ISSUE TITLE
Plan tasks for all group members to work through during Herbie meetings---stress testing

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#142]
First draft:
- [x] sqrt(x+1) - sqrt(x): everyone submit at the same time, everyone hit Improve at the same time
- [x] sqrt(x+1.(...)) - sqrt(x): everyone submit at the same time, everyone hit Improve at the same time (defeat any server caching)
- [ ] if server gets knocked over, does cache get flushed, or is the work saved? might be good for avoiding slowdown, might be bad for keeping buggy output?
- [ ] sqrt(x+1.(...)) - sqrt(x): everyone submit at the same time, then click Improve ASAP (mixture of types of calls)
- [ ] Some larger expression that takes longer to improve in Herbie? Anything from Ben's examples?
- [x] Rapidly clicking on different points to submit analysis requests
- [ ] Some people running FPTaylor tool

**Comment by elmisback** [comment]
Check on this in RA meeting Thursday.

**Comment by elmisback** [comment]
Rapidly clicking points while many improve jobs were running resulted in slowdown and eventual page crash(!).

Could mitigate slowdown by dedicating a thread to analysis calls?

Not sure about page crash.

I crashed the page using sqrt(x+1.(...)) - sqrt(x)  and a single Improve call with lots of clicking while the server was under load.

**Comment by elmisback** [comment]
Crash had error code 5

**Comment by elmisback** [comment]
Zach: page falls over if Improve submitted over and over -- should probably just block the user from submitting more than one at a time

**Comment by zaneenders** [comment]
The server does not cache to disk right now. So if the server topples over the cache is lost.

**Comment by elmisback** [comment]
Stress testing is ongoing. We need to test with a more recent version of `main`, I'm not sure if the current version that fell over at the end of Ben's talk had threads or not. Server commit has is currently `cd05a706932a72a9634d93a31fadff41edbacc11`

**Comment by elmisback** [comment]
We need to resolve action items from the data we've collected. This probably involves writing unit tests and identifying specific weaknesses to test for, with the goal of validating a server version for the feature freeze.

**Comment by elmisback** [comment]
Resolved action items:
* Prohibit new requests when there is a pending request. I've hacked in solutions for this for point selection => local error and for Improve calls.

**Comment by elmisback** [comment]
I'm going to close this now, it is what it is.
