### ISSUE TITLE
Switch expression LaTeX to use the FPBench server for display (especially in the table)

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#158]
The `mathjs` `.toTex()` function is used in several places (https://github.com/herbie-fp/odyssey/blob/main/src/herbie/ExpressionTable.tsx#L313C84-L313C92, https://github.com/herbie-fp/odyssey/blob/cc777615218c2900668c71421c8348d11fa6db3a/src/herbie/ExpressionTable.tsx#L172) to get the LaTeX for an expression, but instead a call to the FPBench compiler on the server should be used.

**Comment by elmisback** [comment]
Tentatively assigning to Jaela

**Comment by jaelafield** [comment]
See [ExpressionExport.tsx](https://github.com/herbie-fp/odyssey/blob/main/src/herbie/ExpressionExport.tsx)

**Comment by jaelafield** [comment]
I have started this & plan to finish it later tonight.

**Comment by jaelafield** [comment]
Do we want expression export tex to also have the exp(x) = part removed? 
t![Image](https://github.com/user-attachments/assets/c953d116-51c0-4afb-8355-96e019e9f929)

**Comment by elmisback** [comment]
Sure, good catch!

**Comment by jaelafield** [comment]
Sounds good! I just pushed the fix.
