### ISSUE TITLE
Nit on UI changes.

### ISSUE THREAD

**Issue by zaneenders** [herbie-fp/odyssey#160]
Small Nit on Odyssey UI updates. Looks great overall

- The math.js is hard to read and IMO it's a little hard to understand it's a toggle til you click on it. 
- Visually hard to tell that "show an example" is a button.
- "Explore" white on light blue could have more contrast between the FG and BG.
- "connected" green is very bight also could have more contrast between the FG and BG.

<img width="136" alt="Screenshot 2024-11-06 at 11 43 55 AM" src="https://github.com/user-attachments/assets/6c71ec64-3184-4700-9ecc-1407f690f193">
<img width="136" alt="Screenshot 2024-11-06 at 11 44 03 AM" src="https://github.com/user-attachments/assets/c706a670-6cfd-409e-b3ef-a44f1a5209bf">
<img width="384" alt="Screenshot 2024-11-06 at 11 43 33 AM" src="https://github.com/user-attachments/assets/b8a45ce3-e316-4194-a2c1-46c8088d6388">
<img width="794" alt="Screenshot 2024-11-06 at 10 57 11 AM" src="https://github.com/user-attachments/assets/458ae861-cda0-4ed7-8e4e-33ecd686abbd">

**Comment by jaelafield** [comment]
Second these! Though the last 2 contrast issues appear to be just a dark mode support issue, in light mode it looks better.

**Comment by elmisback** [comment]
* I removed dark mode to fix contrast issues.
* I assume you're testing in something like Safari and the slider isn't rendering properly. For the presentation, we are focusing on Chrome, but I can try to fix the slider in Safari at some point.
* The button issue is a little complicated, I can maybe do something like adding a drop shadow for this special button.

**Comment by elmisback** [comment]
Added some box shadow. I'll close this, but let me know what browser that was so I can check the slider

**Comment by zaneenders** [comment]
Ya that was Safari and my system is always dark mode. I don't use Chrome based browsers unless I need to. I do most web dev with FireFox Dev Edition. 

BTW UI is looking 🔥
