### ISSUE TITLE
Documentation and Issues links not working.

### ISSUE THREAD

**Issue by zaneenders** [herbie-fp/odyssey#162]
The documentation and Issue links in the deployed version of [Odyssey](https://herbie-fp.github.io/odyssey/) don't work. They are missing href but trigger the error below.
<img width="557" alt="Screenshot 2024-11-06 at 1 26 48 PM" src="https://github.com/user-attachments/assets/75122c35-81d0-4ea2-87cd-d9eb21687569">
<img width="595" alt="Screenshot 2024-11-06 at 1 27 15 PM" src="https://github.com/user-attachments/assets/0fa98968-7910-4b2e-9726-cc845d13df00">

**Comment by elmisback** [comment]
There was no reason for these to be sending any message to the host, they just need to open a link. I replaced and removed the components for these buttons.
