### ISSUE TITLE
Derivations colors in darkmode

### ISSUE THREAD

**Issue by zaneenders** [herbie-fp/odyssey#163]
The default blue in Derivations is a little hard to read depending on the state of the background and also IMO implies the text is a link to something else.

<img width="870" alt="Screenshot 2024-11-06 at 2 33 40 PM" src="https://github.com/user-attachments/assets/3d4eac02-b03f-40f1-95bf-d296ce407eb7">

**Comment by elmisback** [comment]
I need to just turn off dark mode for now, it's not fully implemented or consistent across platforms.

**Comment by elmisback** [comment]
Closing this for now, we can reopen if we want to focus on supporting dark mode.
