### ISSUE TITLE
Large expressions cause visualizations half of screen to be really small

### ISSUE THREAD

**Issue by jaelafield** [herbie-fp/odyssey#173]
Previously, large expressions expanded so much that error plot (and others) would be too small to see.

Options to fix: make center divide draggable so plot/expression table portions can be expanded/shrunk (may be a valuable feature regardless), or put limit on size of expressions table

**Comment by jaelafield** [comment]
This problem may already be fixed, though see new [issue](https://github.com/herbie-fp/odyssey/issues/172)

**Comment by jaelafield** [comment]
Example problematic expression:
`sqrt(x+1) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - ((sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x)) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) sqrt(x+1) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x) - sqrt(x))`

() are problematic, the many `sqrt(x+1) - sqrt(x) - sqrt(x)...` expression on it's own doesn't have a LaTeX issue.

Breaks TeX on landing page:
![Image](https://github.com/user-attachments/assets/a2a05d2e-6e93-48c2-aeb2-075f04b3ede4)
Breaks TeX in expression table:
![Image](https://github.com/user-attachments/assets/0c245241-c2b7-45c5-9331-4f6c4fd3527e)

**Comment by elmisback** [comment]
I hacked a quick fix for this
