### ISSUE TITLE
Reach out to Cindy and Ganesh, get examples of expressions and maybe set up meetings

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#175]

**Comment by elmisback** [comment]
We've done this, now we need to turn the responses into a plan for an example or two we can present

**Comment by benwang33** [comment]
Yep, understood. I will admit I don't understand everything mentioned in the email chain, so I will need to read through again to make sure I know.

**Comment by elmisback** [comment]
Dolores ran Herbie on examples that Ciel proves has issues--in some cases Herbie rewrite prevents the compiler variation!

**Comment by elmisback** [comment]
I think this is basically done, we can incorporate anything Dolores gives us, but mostly this just gives us context we can speak from.
