### ISSUE TITLE
Only change selection of one point.

### ISSUE THREAD

**Issue by zaneenders** [herbie-fp/odyssey#185]
Currently, when you select a different point, it changes the selection in all variables. I think we only want to change the selected point for the clicked variable. I'm guessing this would need an index per variable on the Odyssey side.

https://github.com/user-attachments/assets/531e97a0-9a20-499a-8ec9-c4cb9bf4e0a5

**Comment by elmisback** [comment]
The selected point has values for each variable, so all variables have to change unless we resample for now
