### ISSUE TITLE
Hitting enter on add expression inserts a new line and displays a warning.

### ISSUE THREAD

**Issue by zaneenders** [herbie-fp/odyssey#192]
Herbie: 9287265  Odyssey: 8da4444
I don't know if this is really an issue, as not every text box supports hitting enter to submit and then you have to figure out if `shift-enter` works or if that's the submit command. Current behavior is probably fine.

https://github.com/user-attachments/assets/7de9dcad-84e3-43bd-8532-5800923f8519

**Comment by elmisback** [comment]
Quick solution, strip whitespace from start/end of expression @jaelafield

**Comment by jaelafield** [comment]
Fixed in [671c390](https://github.com/herbie-fp/odyssey/commit/671c3908a0640ad564062e2ed1b14a95fecbf637)
