### ISSUE TITLE
Missing range input areas

### ISSUE THREAD

**Issue by jaelafield** [herbie-fp/odyssey#206]
All range input areas (except the last) are missing after pasting an input into the spec input area
<img width="1463" alt="Screenshot 2024-11-13 at 6 13 19 PM" src="https://github.com/user-attachments/assets/b846530e-f75b-446a-b563-d22a1fdf56bb">

If you type especially quickly or paste in just part of the input, sometimes areas other than the last are missing also.

**Comment by jaelafield** [comment]
@elmisback I've spent some time diagnosing this, but I need to move on to doing something else right this minute (and maybe won't get back to it tonight), but I thought I'd put my diagnosis out there in case that helps you knock it out if you'd like to right now.

This issue seems to be a state bug with this [line](https://github.com/herbie-fp/odyssey/blob/1f658e82739a2af86a7bf453bd3488b992143cab/src/herbie/SpecComponent.tsx#L349)
The `setMySpecRanges` that happens just below this is, of course, not instantaneous. So here when we iterate over the variables and add a `new SpecRange` for _multiple_ new variables, `mySpecRanges` holds it's non-updated value on each iteration, so only the last addition actually sticks and gets reflected in the `setMySpecRanges` update.

**Comment by jaelafield** [comment]
Extra update, I doubt I'll be able to look at this before the RA meeting tomorrow either, I'm so sorry! But hopefully that ^^ is helpful.

**Comment by elmisback** [comment]
Thanks for isolating this to paste--basically the issue was that initialization isn't handled properly. I added a useEffect that initializes uninitialized ranges whenever new variables are detected.
