### ISSUE TITLE
Optimization: only calculate local error for currently expanded expression

### ISSUE THREAD

**Issue by jaelafield** [herbie-fp/odyssey#210]
Currently do know which local errors are visible, so can expand that to only make a call for those local error analyses. These analyses calls are expensive, so this should speed things up, especially when there are many expressions.

- Currently visible local error is list of indices, better to store IDs
- Make list global & use to inform if local error calls are made

**Comment by elmisback** [comment]
Implemented

**Comment by jaelafield** [comment]
nice
