### ISSUE TITLE
Mermaid html briefly showing for Local Error.

### ISSUE THREAD

**Issue by zaneenders** [herbie-fp/odyssey#215]
I don't have a screenshot of this as I can't seem to reproduce it locally. During the Odyssey meeting, we noticed that after selecting a point there was a brief moment when the raw HTML/Mermaid text was visible before the SVG was drawn. Briefly looking at the network tab there is roughly 131Kb of Mermaid related data loading at that time.

**Comment by zaneenders** [comment]
<img width="867" alt="Screenshot 2024-11-14 at 6 03 57 PM" src="https://github.com/user-attachments/assets/a825b2d0-9ecb-4ffb-891a-af850ec05c2b">
Screenshot from the networking tab. Showing all the loaded data after the `explanations` and `localerror` requests.

**Comment by elmisback** [comment]
This should be fixed by Parth's work in 80b380d
