### ISSUE TITLE
Overscrolling still happens to the length of the list of expressions (Mac Chrome)

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#221]
Happens for quadratic after 1 improve: (-b + sqrt(b^2 - 4a*c))/(2a)

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/bb42f1d5-23c8-4d62-86e4-6e4e4c658eb4">

**Comment by jaelafield** [comment]
I fixed this when I fixed #209
