### ISSUE TITLE
Pareto point selection not selecting correct expression in table

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#78]
I thought this was fixed, but I'm still seeing the pareto point selection bug. Maybe there was a bad merge? Can you check the code for this @benwang33 ?

**Comment by elmisback** [comment]
E.g. when I click the purple point below it selects the red point:
![image](https://github.com/user-attachments/assets/d3dbaf52-b28d-4c01-a4c4-917753287b2a)

**Comment by benwang33** [comment]
Ahh yes, this bug is still here. I pivoted off of working on this to finish the LinkToReports component last week, I can return to fix it.

**Comment by benwang33** [comment]
Update: No meaningful progress unfortunately. This bug is a pain :(((

**Comment by elmisback** [comment]
My immediate guess is that this occurs due to sorting of some kind. Maybe collaborate with @jaelafield on solving this? We can also have a look during the meeting if there's time.
