### ISSUE TITLE
State of previous spec exploration not cleared when spec changes

### ISSUE THREAD

**Issue by jaelafield** [herbie-fp/odyssey#89]
When you have a point selected and change the spec and then return, the point stays "selected":
<img width="1464" alt="Screenshot 2024-08-16 at 3 19 45 PM" src="https://github.com/user-attachments/assets/734e15bf-84d3-4df4-abb7-e52d166b8f90">
<img width="1464" alt="Screenshot 2024-08-16 at 3 20 06 PM" src="https://github.com/user-attachments/assets/e04af816-1177-45d0-be9c-387aad15405e">

This causes an error when switching from a 1 variable expression to a 2 variable expression while a point is selected:
```
Error: Error sending data to Herbie server at http://127.0.0.1:8000/api/localerror:
**Herbie server: map: all lists must have same size
  first list length: 1
  other list length: 2**
  procedure: #<procedure:real->repr>
  context...:
   .../private/map.rkt:257:2: gen-map
   .../src/points.rkt:88:0: json->pcontext
   .../web/demo.rkt:472:4
   .../web/demo.rkt:304:2
   .../private/arrow-higher-order.rkt:375:33
   [repeats 1 more time]
   .../dispatchers/dispatch-servlets.rkt:63:2
   .../private/dispatch-server-with-connect-unit.rkt:101:2

    at getHerbieApi (https://file+.vscode-resource.vscode-cdn.net/Users/jaelafield/UW/PLSE/odyssey/dist/webview.bundle.js:130632:15)
    at async analyzeLocalError (https://file+.vscode-resource.vscode-cdn.net/Users/jaelafield/UW/PLSE/odyssey/dist/webview.bundle.js:130652:13)
    at async Object.run [as analyzeLocalError] (https://file+.vscode-resource.vscode-cdn.net/Users/jaelafield/UW/PLSE/odyssey/dist/webview.bundle.js:128738:24)
    at async getPointLocalError (https://file+.vscode-resource.vscode-cdn.net/Users/jaelafield/UW/PLSE/odyssey/dist/webview.bundle.js:128997:102)
```

Also, the old spec ('x + y') remains visible in header when changing to a new spec:
<img width="1463" alt="Screenshot 2024-08-16 at 3 02 48 PM" src="https://github.com/user-attachments/assets/253daba6-dd67-4e15-8217-87af8ba193c6">
Seems problematic since you can't actually return to 'x + y' without re-'explore'ing that formula. (Being able to return to 'x + y' seems like a good idea, or at least having a better confirmation that clicking on that spec in the header will mean exiting the 'explore' area, even a simple tooltip could do the job.)

**Comment by jaelafield** [comment]
@elmisback the error is the bug that came up during a meeting once, I finally reproduced it and realized what was going on. There's a couple things here, but I assume the fix is the same & likely in the same spot (clearing selected point and spec when returning to the spec page).

**Comment by elmisback** [comment]
Nah, this makes sense and is easy to fix! Thanks for the clear report, I will knock this out!
